name: AstralV2
version: ${version}
main: dev.astralv2.AstralPlugin
api-version: '1.21'
authors: [Astral]
description: OpenWorld RPG core plugin for Astral project.
commands:
  astral:
    description: Astral main command.
    usage: /<command> <stats|anomaly|dungeon|event|leaderboard|statset|statadd|statreset>
    aliases: [as]
    permission: astral.user
permissions:
  astral.user:
    description: Basic Astral command access.
    default: true
  astral.admin:
    description: Astral admin commands.
    default: op
